### ISSUE TITLE
Invalid peer dependencies

### ISSUE THREAD

**Issue by boyeln** [lxsmnsyc/dismantle#6]
The `vite-plugin-use-server-directive` has a [peer dependency on `use-server-directive@^0.3.0`](https://github.com/lxsmnsyc/dismantle/blob/7f42f2d2f0f0968ca6810e111a1ed71d57447983/use-server-directive/vite/package.json#L40) in the latest version. Normally the caret-range matches anything with an equal or higher semver within the same major version. However, since these packages haven't reached 1.0 yet, the caret-range requires the minor version to be the same. When testing out the vite plugin, it seems like the latest version of `vite-plugin-use-server-directive` (0.4.2) is incompatible with `use-server-directive@0.3.0`. However, the package manager is not happy when you force `use-server-directive` to 0.4.2, and complains loudly about invalid peer dependencies.

This would be fixed bu bumping the peer dependency on `use-server-directive` inside `vite-plugin-use-server-directive` to `^0.4.0` (and remembering to either bump it again when reaching 0.5.x, or adding a `||`).

**Comment by lxsmnsyc** [comment]
ah right, thanks. Normally I would do a `>=0.3.0` but I guess the better solution for now would be `>=0.4.0`
